### ISSUE TITLE
StringIndexOutOfBoundsException when running on Travis CI

### ISSUE THREAD

**Issue by massenz** [scoverage/sbt-coveralls#28] opened 2014-11-27 08:04 UTC
Release: 1.0.0.BETA1

This just failed on Travis (but works just fine locally); I used `sbt coverage test coveralls` as the `script:` line in my travis.yml:
```
[info] All tests passed.
[info] Passed: Total 17, Failed 0, Errors 0, Passed 17
[success] Total time: 88 s, completed Nov 27, 2014 7:47:16 AM
[info] Repository = ./.git
[info] Repository = ./.git
[info] Uploading to coveralls.io succeeded: Job #20.1
[info] https://coveralls.io/jobs/3521899
[info] (results may not appear immediately)
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1911)
	at org.scoverage.coveralls.CoverallsClient.postFile(CoverallsClient.scala:38)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$projectSettings$8.apply(CoverallsPlugin.scala:112)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$projectSettings$8.apply(CoverallsPlugin.scala:61)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
  ...
```

Please note that this very same error happens locally if one does not define `COVERALLS_REPO_TOKEN` (but notice in that case it does not even try to upload - while on Travis it uploaded successfully, then failed).

**Comment by le-doude** [comment] 2015-02-09 02:07
Same thing happens to us on with the following. Tried on jdk7 and 8 (oracle).

    script: sbt clean coverage test
    after_success:
    - ...
    - sbt coveralls

**Comment by jjuraszek** [comment] 2015-02-10 21:34
is there any workaround to upload coverall stats from travis build plan? i have tried setting env variable and coverallsToken in build.sbt but exception is the same

**Comment by jjuraszek** [comment] 2015-02-10 21:52
ok, there is workaround - define on travis COVERALLS_REPO_TOKEN variable AND put coverallsToken := "token" into build.sbt

**Comment by johnynek** [comment] 2015-02-24 22:58
@jjuraszek I see this issue as well. I see it when I am running from Travis-CI. If I understand this correctly: https://github.com/scoverage/sbt-coveralls#travis-ci-integration I should not need a repo key. Are you using coveralls with travis?

**Comment by massenz** [comment] 2015-02-24 23:34
I must confess that the workaround is not very clear (do you have an
example on github we can look at) and also, if you're running this from
Travis CI/Github integration you do *not* want to place the token in the
.travis.yml file as that will make your private publicly visible (and
pretty much all instructions tell you not to)

It would ultimately be great if the authors of sbt-coveralls could fix the
issue from occurring in the first place.

**Comment by rorygraves** [comment] 2015-02-25 06:47
look at:
https://github.com/ensime/ensime-server/blob/master/.travis.yml
For an example of handling your keys securely.

**Comment by massenz** [comment] 2015-02-25 07:24
Thanks, Rory - that was also a great example of what can be done on Travis!

Marco

**Comment by jjuraszek** [comment] 2015-02-25 10:14
my actual setup is applied to private repo so I can't point you to travis plan (also private) or github repo. I will try to describe you how I have achieved working setup:
1. on travis setup env variables:
 COVERALLS_REPO_TOKEN <token from coveralls> (that token from coveralls repo details)
COVERALLS_SERVICE_NAME  travis-pro (I don't know for opensource if it is necessary)
2. installation I have follow from https://github.com/scoverage/sbt-coveralls
section "Installation", "Travis CI Integration"
3. in build.sbt 
coverallsToken := "<same value as COVERALLS_REPO_TOKEN>"

coverallsServiceName := "travis-pro"

after that setup it is working on travis build and from my own shell

**Comment by oltyant** [comment] 2015-03-14 00:33
I've got a public repo in Travis and the same exception raised me many times. Recently I gave it up and started to use Codeship CI where your project are not publicly visible by default (and for free). This is true for repo token as well as you can set this up through the already mentioned COVERALLS_REPO_TOKEN environment variable inside your CI project settings. Eventually I was able to set up everything without any fear that my sensitive data can be seen by the public. I know that this is not a solution for Travis users who has only public repos (and who has very complicated build settings). Nevertheless a real alternative for the really impatient just like me.

**Comment by fommil** [comment] 2015-03-15 10:55
dupe of #20

**Comment by fommil** [comment] 2015-03-15 14:30
@rorygraves vote to close as dupe

**Comment by rorygraves** [comment] 2015-03-15 14:31
Agreed.

**Closed by rorygraves** 2015-03-15 14:31 UTC
