### ISSUE TITLE
Error on multiproject upload

### ISSUE THREAD

**Issue by johnynek** [scoverage/sbt-coveralls#36] opened 2015-02-10 21:46 UTC
See: https://github.com/twitter/chill/pull/217

Specifically the error message here:
https://travis-ci.org/twitter/chill/jobs/50245868#L1399

There is some partial success, but it seems to only upload some of the results even though the log seems to show that coverage data was generated for all the subprojects.

**Comment by fommil** [comment] 2015-02-13 22:14
yup, I'm seeing the same thing, e.g. https://travis-ci.org/fommil/lions-share/builds/50696488

**Comment by fommil** [comment] 2015-03-10 22:51
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1949)
	at org.scoverage.coveralls.CoverallsClient.postFile(CoverallsClient.scala:38)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$projectSettings$8.apply(CoverallsPlugin.scala:112)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$projectSettings$8.apply(CoverallsPlugin.scala:61)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.j
```

**Comment by fommil** [comment] 2015-03-15 10:52
dupe of #28

**Comment by fommil** [comment] 2015-03-15 14:30
@rorygraves vote to close as dupe

**Comment by rorygraves** [comment] 2015-03-15 14:30
Closed as dupe

**Closed by rorygraves** 2015-03-15 14:30 UTC
