### ISSUE TITLE
Instrumentation metrics are not found if Travis build is done in 2 stages.

### ISSUE THREAD

**Issue by alexflav23** [scoverage/sbt-coveralls#85] opened 2016-03-14 10:52 UTC
In TravisCI, you can schedule execution of the `coveralls` command on an `after_success` call just like it is advised. Option 1 for the sake of argument

_Option 1_

```
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success: 
- sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls
```

The interesting problem, perhaps caused by the `++$TRAVIS_SCALA_VERSION`, is that when the `after_success` phase is triggered, the `cobertura.xml` alongside other relevant files are not found, and the build fails to submit anything to coveralls or to generate a final coverage report or aggregate it.
- Option 2*

This one inlines all the necessary plugin executions in one single build stage, the `script` stage. This works because the exit code of every stage appears to be propagated adequately to every other stage to follow, so there won't be any attempts to run coverage on failed builds and so on.

```
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate coveralls
```

The above works like a charm and adequately submits all the right stuff. The problem now is however we would like fine grained control over things like only attempting to submit coverage for a single build variant(one Scala+JDK combo), but `coverageReport` will fail as soon as the build goes "in and out" of SBT.

Is there any way to fix this?

**Comment by gslowikowski** [comment] 2018-05-01 12:14
This is interesting problem. It can be caused by different `$TRAVIS_SCALA_VERSION` values in different build steps.

@alexflav23 please help me verify this. Modify your build this way:
```
script:
- sbt ++$TRAVIS_SCALA_VERSION "show scalaVersion" clean coverage test
after_success: 
- sbt ++$TRAVIS_SCALA_VERSION "show scalaVersion" coverageReport coverageAggregate coveralls
```
and check if printed Scala version is the same in both steps.

**Comment by alexflav23** [comment] 2018-05-01 12:17
Hi @gslowikowski That's a fair point, but that's impossible. I will of course endeavour to double check, but there would be a lot of other stuff breaking is the Scala version would diverge, which leads me to believe something else weird happens.

And it's possibly a magic Travis cleanup phase they are not sharing the details of.

**Comment by rolandtritsch** [comment] 2022-11-26 17:35
Old. Closing. Please reopen when needed.

**Closed by rolandtritsch** 2022-11-26 17:35 UTC
